# Generated by Django 4.2.4 on 2023-08-08 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTraits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charisma', models.IntegerField(default=0)),
                ('dexterity', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='GameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_battle', models.CharField(max_length=255)),
                ('health', models.IntegerField(default=15)),
                ('level', models.IntegerField(default=1)),
                ('story_section', models.CharField(max_length=10)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player_app.player')),
            ],
        ),
    ]
