# Generated by Django 4.2.4 on 2023-08-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprogress',
            name='damage',
            field=models.IntegerField(default=0),
        ),
    ]
