# Generated by Django 4.2.4 on 2023-08-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0002_gameprogress_damage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playertraits',
            old_name='player',
            new_name='player_traits',
        ),
    ]
