# Generated by Django 4.2.4 on 2023-08-09 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0004_alter_playertraits_player_traits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playertraits',
            name='player_traits',
        ),
        migrations.AddField(
            model_name='playertraits',
            name='player',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='player_app.player'),
        ),
    ]
