# Generated by Django 4.2.4 on 2023-08-09 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0006_alter_playertraits_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertraits',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_traits', to='player_app.player'),
        ),
    ]
