# Generated by Django 4.2.4 on 2023-08-09 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_item_description_alter_inventory_player_and_more'),
        ('player_app', '0007_alter_playertraits_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playertraits',
            name='player',
        ),
        migrations.AddField(
            model_name='playertraits',
            name='name',
            field=models.CharField(default='idk', max_length=255),
        ),
        migrations.AlterField(
            model_name='gameprogress',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player_app.playertraits'),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
