# Generated by Django 4.2.4 on 2023-08-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0009_playertraits_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertraits',
            name='name',
            field=models.CharField(default='The Nameless', max_length=255),
        ),
    ]
