# Generated by Django 4.2.4 on 2023-08-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monster',
            old_name='custom_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='dnd_name',
        ),
        migrations.AddField(
            model_name='monster',
            name='health',
            field=models.IntegerField(default=5),
        ),
    ]
